language: python
dist: bionic
python:
  - 3.7

git:
  submodules: false

before_install:

install:

jobs:
  include:
    - stage: test
      env:
        QGIS_TEST_VERSION="latest"
      script: docker-compose -f .docker/docker-compose.travis.yml run qgis /usr/src/.docker/run-docker-tests.sh

    - stage: deploy
      if: tag IS present
      install:
        - pip install qgis-plugin-ci
      script:
        - >
          qgis-plugin-ci release ${TRAVIS_TAG}
          --transifex-token ${TX_TOKEN}
          --github-token ${GH_TOKEN}
          --osgeo-username ${OSGEO_USERNAME}
          --osgeo-password ${OSGEO_PASSWORD}

    - stage: deploy
      if: branch = master
      install:
        - pip install qgis-plugin-ci
      script: qgis-plugin-ci push-translation ${TX_TOKEN}

env:
  global:
    - OSGEO_USERNAME=mkuhn
    # OSGEO_PASSWORD
    - secure: "ibEhZvG5cDeP9WM2Pw+fM70RKou6sS76NECpUBkf2fN6ygBLPr43Bbl8z5EVhiBAatXQtaMGJQGv4NYHKYpJLxrqJoPmZnlkyMjZwy70AZk25sIIojeNZWczwJRlBlBvAWigpNpDVGn1+Mu3XAbarIrjpYgoKfb3PxH8uQn8YpXPx2YEmndRL4ZUevmQDxPVzRiis8rgr3AVb+oIzKcEdk+pl6MaulLprXQxCOjWFI3ejs2b8VyroZY06sDFoBtNLhXRBp6jzkQKSlmTubtJh/2XAT6Eow31ETwVzldqiqp18T4ipzGFj2a2D5txIfPrCnSxfP/jysf/OjRRQVtGQ3OxOy6+fG6CH55nt9/f/I/9bvJ9RB0OT0zPgr9TRwwy0pkrnF7ST2pyVjQvMSLBjDQu93wmN+ur+/KfOKLTVDdp277DwTsih59Fa4sTDIpP01VNA1s3H2klZxbPdI1TY51why7SMoQKCyw1Cm2nTqPGm8LN7bpLVQ73Et0RACzRDfdPOrN1luh4Fd8Kry45RHyO1+DnbuOzweW2uFwNxx7LdXO2886J53N7y90o/5H/d3CHQ40Wek5jMAzibYWbL2r7K1CStBRqAOAZaaWa4DAyv5pOeING4d5f4veyQMhkcu3774Ltq0X9wlL5pdVMlf7tDP5Xar5bwucePLdSsK0="
    # GH_TOKEN
    - secure: "LhFnNImE1ZajW9gzTXPew3jcX5RF5Yyfbhre2IvVRi7HbUBbax/oR4trAL6Zq+Q6YxMzuhcS6aGithVcr7p39u1YbIdzrj0h9XPWhuF5XlN8TQ7EedtY7fV2fuF3VUQwHdbnxnOMxmKoxSVyMF48F81v9JrGOQ2CupHHD0oT9hHPLMnbEoWnnQ68OxcZTEezOzOgNOCm9HtQaEYDc4mwiSiRbwpyuByXYYOYAFwfMtuXhamHjrHAvtQg66PBIVSN+i1XJokCNbucNeFSe22CEVc9fla1gbFWnj88lht96ezlIiOQUJeZY1WmWMM50iBdb96vRBaiZewo0FZzbu2wIxj3byxu5c+tjvi5VA+aDuQN4ianpg7+UY0kAiAu9RkIdO7ZfomEgNFSutK3YZ9ccW0rxEL7ubD63FvkMjLFYkoxqVS4i3d3rxvCekEZKKD/qaqX8bRoXTjQfrJz9+OZYqVmklHlE/JxZRtGbgMu5eimew5uB1np9mPAIEUoNc3FiYOpTZ9g8KLKIUfzGdqHcClV3DCzuqOdP8RXZe2d/yb4zmM5iqRnTsPj3Z7c5D4NJDdKuqy0u08LRhBiCCH0ZUF6t6MSgrA+EQtGiS6jTQWvAYeXTnHP/O3wbgWrMsTrIyn33aODJiTSkRJMgIb0Mg8RWgKmVf1eWOP8ib8cDXA="
    # TX_TOKEN
    - secure: "nIUDcSo76qRL8+uZakPg/AGI/X0IIwnsvq1Alk5GX3z+8ojQyFGL4UT+R2NAsRqs3VOo5CSpLVfcgW/+P+xH/UKheu9SiGObYlPsEJaukFxlUY4tOVRSHQZn5LUpUvvE8J8ZNxsOZWWqNtznw5Scc910cZQQhpSOyyaiPGGbXKd3cZza8msgbspmJKK3C0Sr0DcuUItafEBsO6zHiL8bGbC+TAFiDDuVE0Fh7r9cEBjo+kydDt8ddSWO1IU/InQJ+yEjzxHHTIKH6NoIwjulaLNScL+CrmEognn04QC6pmpIlZ6wur+MhnuOedm2kCQwwz9u1BDK/JDxRNG56ZY4nLAT5ji+aAU0wa+N1G9aveXWcO2NKNib3e8GAlCLgN3srCF776ryvXKxb7TnB9TnUCT3Ki5NbUZiZ6iCSBCt/OpYoLaQDNP0JXVASqmU7h6LVeIhG8JaUlGDGSJgSjQDCXBum2Nhja5ihIpAHYB+JDozYgNrobwEXnfNsSvX85eoOPp7jxfL2BztUAzT7X0pYp104M/RAEKLO031ok+nMwBbUgYSMqCJVEQTb6I/ZZhjpjk1fUg/fJK7aGGzzb+mU4mlTWqD1m6K+q+WSxOyd3bfTwKqmeXzonqMcdfmhDyCQG+SgCywFkQu02s+EHGB8zA25Xm3c8Qk+r0Iu41v2zo="
