language: python

python:
  - 3.5

addons:
  apt:
    packages:
      - pyqt5-dev-tools

git:
  submodules: false

before_install:
#  - >-
#    openssl aes-256-cbc
#    -K $encrypted_0b023fb27a48_key
#    -iv $encrypted_0b023fb27a48_iv
#    -in github_deploy_key.enc
#    -out github_deploy_key.out
#    -d
#  - chmod 600 github_deploy_key.out
#  - eval $(ssh-agent -s)
#  - ssh-add github_deploy_key.out
  - git submodule update --init --recursive

install:
  - pip install -r requirements.txt

jobs:
  include:
    - stage: text
      script:
        - flake8 --jobs=1
        - xvfb-run nose2

    - stage: deploy
      if: tag IS present
      script: plugin_ci/release/release.sh

env:
  global:
    # OSGEO credentials to release the plugin
    # Generate with the following command for proper special characters support
    # travis encrypt OSGEO_PASSWORD=\''Your super secret password!'\'
    - OSGEO_USERNAME=mkuhn
    - secure: "ibEhZvG5cDeP9WM2Pw+fM70RKou6sS76NECpUBkf2fN6ygBLPr43Bbl8z5EVhiBAatXQtaMGJQGv4NYHKYpJLxrqJoPmZnlkyMjZwy70AZk25sIIojeNZWczwJRlBlBvAWigpNpDVGn1+Mu3XAbarIrjpYgoKfb3PxH8uQn8YpXPx2YEmndRL4ZUevmQDxPVzRiis8rgr3AVb+oIzKcEdk+pl6MaulLprXQxCOjWFI3ejs2b8VyroZY06sDFoBtNLhXRBp6jzkQKSlmTubtJh/2XAT6Eow31ETwVzldqiqp18T4ipzGFj2a2D5txIfPrCnSxfP/jysf/OjRRQVtGQ3OxOy6+fG6CH55nt9/f/I/9bvJ9RB0OT0zPgr9TRwwy0pkrnF7ST2pyVjQvMSLBjDQu93wmN+ur+/KfOKLTVDdp277DwTsih59Fa4sTDIpP01VNA1s3H2klZxbPdI1TY51why7SMoQKCyw1Cm2nTqPGm8LN7bpLVQ73Et0RACzRDfdPOrN1luh4Fd8Kry45RHyO1+DnbuOzweW2uFwNxx7LdXO2886J53N7y90o/5H/d3CHQ40Wek5jMAzibYWbL2r7K1CStBRqAOAZaaWa4DAyv5pOeING4d5f4veyQMhkcu3774Ltq0X9wlL5pdVMlf7tDP5Xar5bwucePLdSsK0="

    # GH_TOKEN for creating releases
    # https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line
    # authrize only "repo_deployment"
    # travis encrypt GH_TOKEN="......"
    - secure: "LhFnNImE1ZajW9gzTXPew3jcX5RF5Yyfbhre2IvVRi7HbUBbax/oR4trAL6Zq+Q6YxMzuhcS6aGithVcr7p39u1YbIdzrj0h9XPWhuF5XlN8TQ7EedtY7fV2fuF3VUQwHdbnxnOMxmKoxSVyMF48F81v9JrGOQ2CupHHD0oT9hHPLMnbEoWnnQ68OxcZTEezOzOgNOCm9HtQaEYDc4mwiSiRbwpyuByXYYOYAFwfMtuXhamHjrHAvtQg66PBIVSN+i1XJokCNbucNeFSe22CEVc9fla1gbFWnj88lht96ezlIiOQUJeZY1WmWMM50iBdb96vRBaiZewo0FZzbu2wIxj3byxu5c+tjvi5VA+aDuQN4ianpg7+UY0kAiAu9RkIdO7ZfomEgNFSutK3YZ9ccW0rxEL7ubD63FvkMjLFYkoxqVS4i3d3rxvCekEZKKD/qaqX8bRoXTjQfrJz9+OZYqVmklHlE/JxZRtGbgMu5eimew5uB1np9mPAIEUoNc3FiYOpTZ9g8KLKIUfzGdqHcClV3DCzuqOdP8RXZe2d/yb4zmM5iqRnTsPj3Z7c5D4NJDdKuqy0u08LRhBiCCH0ZUF6t6MSgrA+EQtGiS6jTQWvAYeXTnHP/O3wbgWrMsTrIyn33aODJiTSkRJMgIb0Mg8RWgKmVf1eWOP8ib8cDXA="
