version: '3'
services:
#  postgres:
#    image: kartoza/postgis:10.0-2.4
#    environment:
#      - ALLOW_IP_RANGE="172.0.0.0/8"

  qgis:
    build:
      context: ..
      dockerfile: ./.docker/Dockerfile
      args:
        QGIS_TEST_VERSION: ${QGIS_TEST_VERSION}
    tty: true
    volumes:
      - ${TRAVIS_BUILD_DIR}:/usr/src
#    links:
#      - postgres
